### ISSUE TITLE
Starting a window as scratch pad

### ISSUE THREAD

**Issue by Gavinok** [GasparVardanyan/dwm-scratchpad#1]
Not really an issue I was just wondering if you know of a way to start a window as a scratchpad.? Maybe using the rules feature in dwm. I want to be able to start a specific program as a scratchpad if none exist yet.

**Comment by GasparVardanyan** [comment]
You need to launch that window from dwm, get the **Client \*** variable of that window (from **selmon -> clients**), set the **tags** attribute of that structure to **scratchpad_mask**, call **focus(NULL);arrange(selmon);** and that's it.

**Comment by GasparVardanyan** [comment]
To hide the selected window I use this function:
```c
static void scratchpad_hide ()
{
	if (selmon -> sel)
	{
		selmon -> sel -> tags = scratchpad_mask;
		focus (NULL);
		arrange (selmon);
	}
}
```

**Comment by GasparVardanyan** [comment]
Useful resource: man EXEC(3) https://linux.die.net/man/3/exec

**Comment by Gavinok** [comment]
thanks

**Comment by GasparVardanyan** [comment]
@Gavinok now starting windows in scratchpad is supported. See the README.md.
