### ISSUE TITLE
multiple scratchpads question

### ISSUE THREAD

**Issue by kronikpillow** [GasparVardanyan/dwm-scratchpad#2]
I'v posted this question on your post on reddit as well, but i see its a little old, so here's what im thinking, I see you posted this to luke on his dwm github, my question is, can we have the same thing with your scratchpad as with Luke's I3 config?

for example, on his i3 config when you press MOD+a it opens a bc calculator in a scratchpad, but when you press MOD+y it opens tmux in a scratchpad, while pressing mod+v opens VimwikiIndex (for him) or simply vim for me :) 

and to be able to toggle it with the same keybinding, so that we dont have to use different keybindings for something that could be bound to 1 key

**Comment by GasparVardanyan** [comment]
You need to edit dwm's source code.
You need to launch that windows from dwm, get the **Client \*** variable of that window (from **selmon -> clients**), set the **tags** attribute of that structure to **scratchpad_mask**, call **focus(NULL);arrange(selmon);** and that's it.
To hide the selected window I use this function:
```c
static void scratchpad_hide ()
{
	if (selmon -> sel)
	{
		selmon -> sel -> tags = scratchpad_mask;
		focus (NULL);
		arrange (selmon);
	}
}
```

**Comment by GasparVardanyan** [comment]
Might be useful: man EXEC(3) https://linux.die.net/man/3/exec

**Comment by kronikpillow** [comment]
hm... sounds complicated, I'm not a programmer, just a user ... 

how about implementing a window rule something like inscratchpad 0 1 ... then the app could be predefined to always launch in a scratchpad

**Comment by GasparVardanyan** [comment]
Try to add something like this in **rules**:
	{ NULL,       NULL,       "hidden",   **scratchpad_mask**,            0,           -1 },

And launch something like:
st -t hidden

**Comment by GasparVardanyan** [comment]
@kronikpillow now starting windows in scratchpad is supported. See the README.md.

**Comment by GasparVardanyan** [comment]
Use the namedscratchpads patch ))
