### ISSUE TITLE
floating scratchpad

### ISSUE THREAD

**Issue by ranjithshegde** [GasparVardanyan/dwm-scratchpad#3]
Firstly, thank you for this wonderful feature. More reason to never switch from DWM. 

I have one feature request. Is it possible to show/recall the scratchpad/s in floating mode same as i3/sway?

**Comment by GasparVardanyan** [comment]
You're welcome. I'm happy that you use my patch. Try this:
```diff
gaspar -> [ dwm ] :: git diff dwm.c
diff --git a/dwm.c b/dwm.c
index 4b4afe4..a05f290 100644
--- a/dwm.c
+++ b/dwm.c
@@ -1481,6 +1481,7 @@ static void scratchpad_hide ()
        if (selmon -> sel)
        {
                selmon -> sel -> tags = SCRATCHPAD_MASK;
+               selmon -> sel -> isfloating = 1;
                focus(NULL);
                arrange(selmon);
        }
```

**Comment by GasparVardanyan** [comment]
That seems really nice to have scratchpads in a floating mode ))

**Comment by ranjithshegde** [comment]
@GasparVardanyan Thank you so much! works like a charm. I hope this patch gets to the official patches section on dwm site. Its better than the scratchpad patches on the site!

**Comment by GasparVardanyan** [comment]
Sorry, but I'm so busy nowdays, I'll happy if you submit this patch.
