### ISSUE TITLE
i use both patches with dwm

### ISSUE THREAD

**Issue by kristoferus75** [GasparVardanyan/dwm-scratchpad#4]
Hi !

I want to have two scratchpads for example:

one with st  if i press super + s
and
one with mousepad if i press super + m

and if i press key Super+m  to open mousepad -> ok it works and mousepad open in scratchpad
but if press key Super+s to open st -> mousepad opens in scratchpad and not st 

Can i achive this ?

Thanks !

```
static const Rule rules[]
{ "Mousepad", NULL, NULL, SCRATCHPAD_MASK, 0, -1 },

static const char scratchpadname[] = "scratchpad";
static const char *scratchpadcmd[] = { "st", "-t", scratchpadname, "-g", "120x34", NULL };

static Key keys[]
{ MODKEY|ControlMask,           XK_s,      togglescratch,  {.v = scratchpadcmd } },//Scratchpad
{ MODKEY|ControlMask,             XK_m,    togglescratch,    SHCMD("mousepad") },//Mousepad
```

**Comment by GasparVardanyan** [comment]
Already fixed?
